project:
  type: book

book:
  title: "THESIS"
  author: "BENNOUR MOHAMED HSIN"
  date: "12/3/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - lit_rev.qmd
    - potential.qmd
    - results.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    browser: brave
    theme: cosmo
    lot: true
    lof: true
    fontsize: 12pt
    linestretch: 1.5
    mermaid:
      theme: default

    




